eureka:
  instance:
    hostname: localhost
  server:
    port: 8761
  client:
    service-url:
      defaultZone: http://localhost:${eureka.server.port}/eureka/
spring:
  cloud:
    config:
      override-system-properties: false