spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: alibou
    password: alibou
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  mail:
    host: localhost
    port: 1025
    username: seal
    password: seal
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/seal"
keycloak:
  server-url: http://localhost:9090
  realm: seal
  client-id: ecommerce-application
  client-secret: 0792GxiBR7d0tyxdaEyl9u7yl1mENnSc
server:
  servlet:
    context-path: /api/v1
  port: 8030